name: "crm_sales_analytics"
version: "1.0.0"
config-version: 2

profile: "crm_sales_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  crm_sales_analytics:
    staging:
      +materialized: view
      +schema: STAGING
      +tags: ['staging', 'crm']
