name: "crm_sales_analytics"
version: "1.0.0"
config-version: 2

profile: "crm_sales_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  date_spine_start_date: "2023-01-01"
  date_spine_end_date: "2025-12-31"
  date_spine_rowcount: 5000

models:
  crm_sales_analytics:
    staging:
      +materialized: view
      +schema: STAGING
      +tags: ['staging', 'crm']

    intermediate:
      +materialized: view
      +schema: INTERMEDIATE
      +tags: ['intermediate', 'crm']

    marts:
      +materialized: table
      +schema: MARTS
      +tags: ['mart', 'crm']
