-- ============================================================
-- Create RAW load audit table
-- Project: CRM Sales Analytics Platform
-- ============================================================

USE WAREHOUSE CRM_ANALYTICS_WH;

USE DATABASE CRM_SALES_ANALYTICS;

USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_LOAD_AUDIT (
    table_name VARCHAR,
    loaded_at TIMESTAMP_NTZ
);

INSERT INTO
    RAW_LOAD_AUDIT (table_name, loaded_at)
SELECT 'RAW_REGIONS', CURRENT_TIMESTAMP()
UNION ALL
SELECT 'RAW_CUSTOMERS', CURRENT_TIMESTAMP()
UNION ALL
SELECT 'RAW_PRODUCTS', CURRENT_TIMESTAMP()
UNION ALL
SELECT 'RAW_SALES_REPS', CURRENT_TIMESTAMP()
UNION ALL
SELECT 'RAW_ORDERS', CURRENT_TIMESTAMP()
UNION ALL
SELECT 'RAW_ORDER_ITEMS', CURRENT_TIMESTAMP()
UNION ALL
SELECT 'RAW_OPPORTUNITIES', CURRENT_TIMESTAMP();