USE WAREHOUSE CRM_ANALYTICS_WH;

USE DATABASE CRM_SALES_ANALYTICS;

USE SCHEMA RAW;

TRUNCATE TABLE RAW_REGIONS;

TRUNCATE TABLE RAW_CUSTOMERS;

TRUNCATE TABLE RAW_PRODUCTS;

TRUNCATE TABLE RAW_SALES_REPS;

TRUNCATE TABLE RAW_ORDERS;

TRUNCATE TABLE RAW_ORDER_ITEMS;

TRUNCATE TABLE RAW_OPPORTUNITIES;

COPY INTO RAW_REGIONS
FROM
    @CRM_RAW_STAGE FILES = ('regions.csv.gz') FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT) ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_CUSTOMERS
FROM
    @CRM_RAW_STAGE FILES = ('customers.csv.gz') FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT) ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_PRODUCTS
FROM
    @CRM_RAW_STAGE FILES = ('products.csv.gz') FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT) ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_SALES_REPS
FROM
    @CRM_RAW_STAGE FILES = ('sales_reps.csv.gz') FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT) ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_ORDERS
FROM
    @CRM_RAW_STAGE FILES = ('orders.csv.gz') FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT) ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_ORDER_ITEMS
FROM
    @CRM_RAW_STAGE FILES = ('order_items.csv.gz') FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT) ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_OPPORTUNITIES
FROM
    @CRM_RAW_STAGE FILES = ('opportunities.csv.gz') FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT) ON_ERROR = 'ABORT_STATEMENT';

MERGE INTO RAW_LOAD_AUDIT AS target
USING (
    SELECT 'RAW_REGIONS' AS table_name, CURRENT_TIMESTAMP() AS loaded_at
    UNION ALL
    SELECT 'RAW_CUSTOMERS', CURRENT_TIMESTAMP()
    UNION ALL
    SELECT 'RAW_PRODUCTS', CURRENT_TIMESTAMP()
    UNION ALL
    SELECT 'RAW_SALES_REPS', CURRENT_TIMESTAMP()
    UNION ALL
    SELECT 'RAW_ORDERS', CURRENT_TIMESTAMP()
    UNION ALL
    SELECT 'RAW_ORDER_ITEMS', CURRENT_TIMESTAMP()
    UNION ALL
    SELECT 'RAW_OPPORTUNITIES', CURRENT_TIMESTAMP()
) AS source
ON target.table_name = source.table_name
WHEN MATCHED THEN
    UPDATE SET loaded_at = source.loaded_at
WHEN NOT MATCHED THEN
    INSERT (table_name, loaded_at)
    VALUES (source.table_name, source.loaded_at);
